### ISSUE TITLE
feat: 新規ユーザー登録関連（バックエンド）

### ISSUE THREAD

**Issue by NanyaTK** [NanyaTK/255_RPRO#13]
- [x] phpを用いてデータベースサーバから時間割データを取得
- [x] 登録詳細画面のリストにそれぞれ反映
- [x] 登録ボタンでlocalstrageに保存（何曜日何限がID何を紐づける）

**Comment by NanyaTK** [comment]
@Sopuranoaruto 
feat-#13-signupBackend
というブランチがあるので，git rebaseの次にgit checkout feat-#13-signupBackendとして開発引き継いでほしいかも

**Comment by Sopuranoaruto** [comment]
IDだけの保存にした
