### ISSUE TITLE
feat: 科目詳細画面の作成（フロントエンド）

### ISSUE THREAD

**Issue by NanyaTK** [NanyaTK/255_RPRO#25]
- [x] 時間割をクリックで科目詳細のポップアップの表示

**Comment by amedama-tech** [comment]
@NanyaTK 
これって、 @Sopuranoaruto が作成しているであろう、教科名クリックで欠席回数とか表示される部分に追記したらよいって感じですか？

**Comment by NanyaTK** [comment]
そうです
あと貴環境のdevelopブランチが最新でないと思われるため更新した方がいいです
その際，既に開発を進めている場合，最初から開発しなおす方が手間がかからないと思います

**Comment by amedama-tech** [comment]
> そうです あと貴環境のdevelopブランチが最新でないと思われるため更新した方がいいです その際，既に開発を進めている場合，最初から開発しなおす方が手間がかからないと思います

develop全然最新じゃなかったので今しました。

**Comment by amedama-tech** [comment]
@NanyaTK 
フロントエンドでどこまでやれば良いか分からないんだけど、側はこんな感じで良いですか？
想定と違うかったり、何か追加してほしい内容あれば教えて下さい。_(._.)_
（科目名については、あるとさんが作ったpopu-btnのbackgroundcolorと同様の色が良いです）

後、米のタスクで担当教員についても追加するってあるけど、データはどうする感じですか？
現状は、担当教員の代わりに学科ID表示させています。
![image](https://github.com/user-attachments/assets/ee28c8d8-eb78-4c15-a221-3daedc107df8)

**Comment by NanyaTK** [comment]
役割以上の仕事をしているように見受けられます
リモートブランチの方にpushしていただくと詳しくわかるのですがPR生やしてくれても問題ないです

**Comment by amedama-tech** [comment]
> 役割以上の仕事をしているように見受けられます リモートブランチの方にpushしていただくと詳しくわかるのですがPR生やしてくれても問題ないです

あ、ちなみに今表示してるのはがち適当な変数なので、時間割に表示されてる科目の内容についてのポップアップを出すってのは実装してません【 @Ris561 米田任せです】

多分、バックエンドの方も実装簡単だと思います〜
