### ISSUE TITLE
fix: ED4年後期 月曜3限の教科入れ替わりの修正

### ISSUE THREAD

**Issue by dubuyuichan** [NanyaTK/255_RPRO#89]
## 概要
- ED4年の後期で絞り込み確定すると、月曜3限の保健体育IV-2が電子回路Ⅰになる
  - EJでは確認できず 
- 確定前に月曜の1,2,4限を変更すると電子回路以外も出てくる(確認したのは固体物性Aと海外研修)
  - 月曜3限を変更した場合、他の時限に影響なし

## 再現手順
1. 「電気情報工学科電気電子コース」「後期」で絞り込み->確定
2. 「電気情報工学科電気電子コース」「後期」で絞り込み->月曜(3限以外)をリスト内別科目に変更->確定

## 問題が確認できた環境
- chrome: バージョン 127.0.6533.120
- FireFox: バージョン 128.0.2
- Safari: バージョン 604.1

**Comment by NanyaTK** [comment]
弊Androidでは再現できませんでした
再起動やブラウザのキャッシュ削除も試してみてください

**Comment by NanyaTK** [comment]
> 弊Androidでは再現できませんでした
> 再起動やブラウザのキャッシュ削除も試してみてください

追記:再現できました
修正します

**Comment by NanyaTK** [comment]
v1.3.7にて修正が完了しました
報告ありがとうございました
https://github.com/NanyaTK/255_RPRO/releases/tag/v1.3.7

**Comment by dubuyuichan** [comment]
@NanyaTK 
修正ありがとうございます　体育を受講できて嬉しいです
